export const CHARGES_REQUEST = "CHARGES_REQUEST"
export const CHARGES_SUCCESS = "CHARGES_SUCCESS"
export const CHARGES_FAIL = "CHARGES_FAIL"
export const CHARGES_RESET= "CHARGES_RESET"

export const DELETE_CHARGES_REQUEST = "DELETE_CHARGES_REQUEST"
export const DELETE_CHARGES_SUCCESS = "DELETE_CHARGES_SUCCESS"
export const DELETE_CHARGES_FAIL = "DELETE_CHARGES_FAIL"
export const DELETE_CHARGES_RESET= "DELETE_CHARGES_RESET"