export const CUSTOMER_REQUEST = "CUSTOMER_REQUEST"
export const CUSTOMER_SUCCESS = "CUSTOMER_SUCCESS"
export const CUSTOMER_FAIL = "CUSTOMER_FAIL"
export const CUSTOMER_RESET= "CUSTOMER_RESET"

export const CUSTOMER_BY_ID_REQUEST = "CUSTOMER_BY_ID_REQUEST"
export const CUSTOMER_BY_ID_SUCCESS = "CUSTOMER_BY_ID_SUCCESS"
export const CUSTOMER_BY_ID_FAIL = "CUSTOMER_BY_ID_FAIL"
export const CUSTOMER_BY_ID_RESET= "CUSTOMER_BY_ID_RESET"

export const CUSTOMER_BY_ACC_REQUEST = "CUSTOMER_BY_ACC_REQUEST"
export const CUSTOMER_BY_ACC_SUCCESS = "CUSTOMER_BY_ACC_SUCCESS"
export const CUSTOMER_BY_ACC_FAIL = "CUSTOMER_BY_ACC_FAIL"
export const CUSTOMER_BY_ACC_RESET= "CUSTOMER_BY_ACC_RESET"

export const CUSTOMER_SAVINGS_REQUEST = "CUSTOMER_SAVINGS_REQUEST"
export const CUSTOMER_SAVINGS_SUCCESS = "CUSTOMER_SAVINGS_SUCCESS"
export const CUSTOMER_SAVINGS_FAIL = "CUSTOMER_SAVINGS_FAIL"
export const CUSTOMER_SAVINGS_RESET= "CUSTOMER_SAVINGS_RESET"

export const CREATE_CUSTOMER_REQUEST = "CREATE_CUSTOMER_REQUEST"
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS"
export const CREATE_CUSTOMER_FAIL = "CREATE_CUSTOMER_FAIL"
export const CREATE_CUSTOMER_RESET= "CREATE_CUSTOMER_RESET"


export const UPDATE_CUSTOMER_REQUEST = "UPDATE_CUSTOMER_REQUEST"
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS"
export const UPDATE_CUSTOMER_FAIL = "UPDATE_CUSTOMER_FAIL"
export const UPDATE_CUSTOMER_RESET = "UPDATE_CUSTOMER_RESET"