export const EXCESS_REQUEST = "EXCESS_REQUEST"
export const EXCESS_SUCCESS = "EXCESS_SUCCESS"
export const EXCESS_FAIL = "EXCESS_FAIL"
export const EXCESS_RESET= "EXCESS_RESET"

export const DELETE_EXCESS_REQUEST = "DELETE_EXCESS_REQUEST"
export const DELETE_EXCESS_SUCCESS = "DELETE_EXCESS_SUCCESS"
export const DELETE_EXCESS_FAIL = "DELETE_EXCESS_FAIL"
export const DELETE_EXCESS_RESET= "DELETE_EXCESS_RESET"