export const LOAN_REQUEST = "LOAN_REQUEST"
export const LOAN_SUCCESS = "LOAN_SUCCESS"
export const LOAN_FAIL = "LOAN_FAIL"
export const LOAN_RESET= "LOAN_RESET"

export const CREATE_LOAN_REQUEST = "CREATE_LOAN_REQUEST"
export const CREATE_LOAN_SUCCESS = "CREATE_LOAN_SUCCESS"
export const CREATE_LOAN_FAIL = "CREATE_LOAN_FAIL"
export const CREATE_LOAN_RESET= "CREATE_LOAN_RESET"

export const DELETE_LOAN_REQUEST = "DELETE_LOAN_REQUEST"
export const DELETE_LOAN_SUCCESS = "DELETE_LOAN_SUCCESS"
export const DELETE_LOAN_FAIL = "DELETE_LOAN_FAIL"
export const DELETE_LOAN_RESET= "DELETE_LOAN_RESET"