export const SAVING_REQUEST = "SAVING_REQUEST"
export const SAVING_SUCCESS = "SAVING_SUCCESS"
export const SAVING_FAIL = "SAVING_FAIL"
export const SAVING_RESET= "SAVING_RESET"

export const SINGLE_SAVING_REQUEST = "SINGLE_SAVING_REQUEST"
export const SINGLE_SAVING_SUCCESS = "SINGLE_SAVING_SUCCESS"
export const SINGLE_SAVING_FAIL = "SINGLE_SAVING_FAIL"
export const SINGLE_SAVING_RESET= "SINGLE_SAVING_RESET"

export const CREATE_SAVING_REQUEST = "CREATE_SAVING_REQUEST"
export const CREATE_SAVING_SUCCESS = "CREATE_SAVING_SUCCESS"
export const CREATE_SAVING_FAIL = "CREATE_SAVING_FAIL"
export const CREATE_SAVING_RESET= "CREATE_SAVING_RESET"

export const DELETE_SAVING_REQUEST = "DELETE_SAVING_REQUEST"
export const DELETE_SAVING_SUCCESS = "DELETE_SAVING_SUCCESS"
export const DELETE_SAVING_FAIL = "DELETE_SAVING_FAIL"
export const DELETE_SAVING_RESET= "DELETE_SAVING_RESET"