export const ADD_SETTINGS_REQUEST = "ADD_SETTINGS_REQUEST"
export const ADD_SETTINGS_SUCCESS = "ADD_SETTINGS_FAIL"
export const ADD_SETTINGS_FAIL = "SETTINGS_FAIL"
export const ADD_SETTINGS_RESET= "ADD_SETTINGS_RESET"

export const SETTINGS_REQUEST = "SETTINGS_REQUEST"
export const SETTINGS_SUCCESS = "SETTINGS_SUCCESS"
export const SETTINGS_FAIL = "SETTINGS_FAIL"
export const SETTINGS_RESET= "SETTINGS_RESET"

export const UPDATE_SETTINGS_REQUEST = "UPDATE_SETTINGS_REQUEST"
export const UPDATE_SETTINGS_SUCCESS = "UPDATE_SETTINGS_SUCCESS"
export const UPDATE_SETTINGS_FAIL = "UPDATE_SETTINGS_FAIL"
export const UPDATE_SETTINGS_RESET= "UPDATE_SETTINGS_RESET"
