export const STAFF_REQUEST = "STAFF_REQUEST"
export const STAFF_SUCCESS = "STAFF_SUCCESS"
export const STAFF_FAIL = "STAFF_FAIL"
export const STAFF_RESET= "STAFF_RESET"

export const STAFF_BY_ID_REQUEST = "STAFF_BY_ID_REQUEST"
export const STAFF_BY_ID_SUCCESS = "STAFF_BY_ID_SUCCESS"
export const STAFF_BY_ID_FAIL = "STAFF_BY_ID_FAIL"
export const STAFF_BY_ID_RESET= "STAFF_BY_ID_RESET"

export const ADD_STAFF_REQUEST = "ADD_STAFF_REQUEST"
export const ADD_STAFF_SUCCESS = "ADD_STAFF_SUCCESS"
export const ADD_STAFF_FAIL = "ADD_STAFF_FAIL"
export const ADD_STAFF_RESET= "ADD_STAFF_RESET"

export const UPDATE_PERMISSION_REQUEST = "UPDATE_PERMISSION_REQUEST"
export const UPDATE_PERMISSION_SUCCESS = "UPDATE_PERMISSION_SUCCESS"
export const UPDATE_PERMISSION_FAIL = "UPDATE_PERMISSION_FAIL"
export const UPDATE_PERMISSION_RESET= "UPDATE_PERMISSION_RESET"

export const UPDATE_STAFF_REQUEST = "UPDATE_STAFF_REQUEST"
export const UPDATE_STAFF_SUCCESS = "UPDATE_STAFF_SUCCESS"
export const UPDATE_STAFF_FAIL = "UPDATE_STAFF_FAIL"
export const UPDATE_STAFF_RESET= "UPDATE_STAFF_RESET"

export const DELETE_STAFF_REQUEST = "DELETE_STAFF_REQUEST"
export const DELETE_STAFF_SUCCESS = "DELETE_STAFF_SUCCESS"
export const DELETE_STAFF_FAIL = "DELETE_STAFF_FAIL"
export const DELETE_STAFF_RESET= "DELETE_STAFF_RESET"