export const WITHDRAWAL_REQUEST = "WITHDRAWAL_REQUEST"
export const WITHDRAWAL_SUCCESS = "WITHDRAWAL_SUCCESS"
export const WITHDRAWAL_FAIL = "WITHDRAWAL_FAIL"
export const WITHDRAWAL_RESET= "WITHDRAWAL_RESET"

export const CREATE_WITHDRAWAL_REQUEST = "CREATE_WITHDRAWAL_REQUEST"
export const CREATE_WITHDRAWAL_SUCCESS = "CREATE_WITHDRAWAL_SUCCESS"
export const CREATE_WITHDRAWAL_FAIL = "CREATE_WITHDRAWAL_FAIL"
export const CREATE_WITHDRAWAL_RESET= "CREATE_WITHDRAWAL_RESET"