export const WITHDRAWAL_REQUEST = "WITHDRAWAL_REQUEST"
export const WITHDRAWAL_SUCCESS = "WITHDRAWAL_SUCCESS"
export const WITHDRAWAL_FAIL = "WITHDRAWAL_FAIL"
export const WITHDRAWAL_RESET= "WITHDRAWAL_RESET"