export const WITHDRAWAL_REQUEST = "WITHDRAWAL_REQUEST"
export const WITHDRAWAL_SUCCESS = "WITHDRAWAL_SUCCESS"
export const WITHDRAWAL_FAIL = "WITHDRAWAL_FAIL"
export const WITHDRAWAL_RESET= "WITHDRAWAL_RESET"

export const CUSTOMER_WIDTHDRAWALS_REQUEST = "CUSTOMER_WIDTHDRAWALS_REQUEST"
export const CUSTOMER_WIDTHDRAWALS_SUCCESS = "CUSTOMER_WIDTHDRAWALS_SUCCESS"
export const CUSTOMER_WIDTHDRAWALS_FAIL = "CUSTOMER_WIDTHDRAWALS_FAIL"
export const CUSTOMER_WIDTHDRAWALS_RESET= "CUSTOMER_WIDTHDRAWALS_RESET"

export const SINGLE_WIDTHDRAWALS_REQUEST = "SINGLE_WIDTHDRAWALS_REQUEST"
export const SINGLE_WIDTHDRAWALS_SUCCESS = "SINGLE_WIDTHDRAWALS_SUCCESS"
export const SINGLE_WIDTHDRAWALS_FAIL = "SINGLE_WIDTHDRAWALS_FAIL"
export const SINGLE_WIDTHDRAWALS_RESET= "SINGLE_WIDTHDRAWALS_RESET"

export const CREATE_WITHDRAWAL_REQUEST = "CREATE_WITHDRAWAL_REQUEST"
export const CREATE_WITHDRAWAL_SUCCESS = "CREATE_WITHDRAWAL_SUCCESS"
export const CREATE_WITHDRAWAL_FAIL = "CREATE_WITHDRAWAL_FAIL"
export const CREATE_WITHDRAWAL_RESET= "CREATE_WITHDRAWAL_RESET"